---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Karsten Schuldt"
title: "Pflanzen auf Photos von Bibliotheken. Essay"
pdf: master.pdf
date: 2020-12-20
comments: false
sharing: true
footer: true

---