---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Rina Jost
- Redaktion LIBREAS
title: "Interview mit Rina Jost"
pdf: "https://doi.org/10.18452/23470"
doi: "10.18452/23470"
date: 2020-12-13
comments: false
sharing: true
footer: true

---