---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Tim Schumann"
title: "<q>It‘s the end of the World as we know it</q>"
subtitle: "Ein Essay über Öffentliche Bibliotheken als zentrale lokale Einrichtung, dem Klimakollaps zu begegnen und ein Werkstattbericht aus der Heinrich-Böll-Bibliothek / Stadtbibliothek Pankow"
pdf: master.pdf
date: 2020-12-20
comments: false
sharing: true
footer: true

---