---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial LIBREAS #38: Tiere und Gewächse"
pdf: "https://doi.org/10.18452/23462"
doi: "10.18452/23462"
date: 2020-12-22
comments: false
sharing: true
footer: true

---
