---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Andréa E. Bhend
title: "Schädlingsmonitoring in einer Bibliothek mit Standort in der Altstadt"
abstract: "Mit dem Rückumzug der Buch- und Kartenbestände in die vollrenovierte Bibliothek Münstergasse in Bern wurde die Chance genutzt, das Schädlingsmonitoring vor Ort neu aufzugleisen. In diesem Artikel wird aufgezeigt und beispielhaft erklärt, worauf insbesondere zu achten ist und wie vorbeugende Massnahmen innerhalb eines IPM (Integrated Pest Management) aussehen können."
altabstract: "With the moving of our archives into the Library Münstergasse in Bern after a major renovation, the opportunity has been used to reinstall a new pest monitoring on-site. This article shows the main factors for monitoring and preventive measures within an IPM-Program (Integrated Pest Management)."
pdf: "https://doi.org/10.18452/23467"
doi: "10.18452/23467"
date: 2020-12-13
comments: false
sharing: true
footer: true

---