---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Katharina Therese Gietkowski
title: "Was lebt denn da? Mikroben in mittelalterlichen Handschriften"
pdf: "https://doi.org/10.18452/23466"
doi: "10.18452/23466"
date: 2020-12-13
comments: false
sharing: true
footer: true

---