---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Judith Zaugg
- Redaktion LIBREAS
title: "Neun Fragen an die Illustratorin Judith Zaugg"
pdf: "https://doi.org/10.18452/23469"
doi: "10.18452/23469"
date: 2020-12-13
comments: false
sharing: true
footer: true

---