---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Judith Zaugg
- Redaktion LIBREAS
title: "9 Fragen an die Illustratorin Judith Zaugg"
pdf: "master.pdf"
date: 2020-12-13
comments: false
sharing: true
footer: true

---