---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Elisa Herrmann
title: "Naturschutzgebiet Bibliothek"
pdf: "master.pdf"
date: 2020-12-13
comments: false
sharing: true
footer: true

---