---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Elisa Herrmann
title: "Naturschutzgebiet Bibliothek"
abstract: "Die Biodiversität in Bibliotheken ist oft erst auf den zweiten Blick erkennbar. In, zwischen und auf Büchern haben ganz besondere Arten ihre biologische Nische eingerichtet – teils vom Menschen gewollt, teils ungewollt. Der Beitrag gibt einen Einblick in die Vielfalt an Organismen in Bibliotheken und die Rolle von Informationsinfrastrukturen zum Schutz von Flora und Fauna der Welt."
abstractalt: "Biodiversity in libraries is often only visible at second glance. Very special species have established their biological niche in, on and between books - partly wanted by humans, partly unwanted. This article provides an insight into the diversity of organisms in libraries and the role of information infrastructures in the protection of the earth’s flora and fauna."
pdf: "https://doi.org/10.18452/23465"
doi: "10.18452/23465"
date: 2020-12-13
comments: false
sharing: true
footer: true

---