---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Janet Wagner
- Tim Schumann
- Christina Riesenweber
title: "Libraries4Future &mdash; über die Initiative und Best Practices"
pdf: "https://doi.org/10.18452/23473"
doi: "10.18452/23473"
date: 2020-12-13
comments: false
sharing: true
footer: true

---