---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Franziska Corradini"
title: "Einfluss der Agenda 2030 auf die deutschsprachige Bibliothekswelt"
pdf: "https://doi.org/10.18452/23476"
doi: "10.18452/23476"
date: 2020-12-20
comments: false
sharing: true
footer: true

---