---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Marjorie Platon"
title: "Farewell Gundula! Obituary to our library plant!"
pdf: master.pdf
date: 2020-12-20
comments: false
sharing: true
footer: true

---