---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Nicole Schuck
- Martina Rißberger
- Redaktion LIBREAS
title: "Interview mit Nicole Schuck und Martina Rißberger: Zwischen Naturwissenschaft und Bildender Kunst – eine künstlerische Perspektive auf naturhistorische Medien"
pdf: "master.pdf"
date: 2020-12-14
comments: false
sharing: true
footer: true

---