---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Heike Ehrlicher"
- "Franziska Baetcke"
title: "Was bisher geschah und was damit erreicht wurde: Ein Zwischenbericht zur Kampagne Biblio2030 des Schweizer
Bibliotheksverbands Bibliosuisse"
pdf: master.pdf
date: 2020-12-20
comments: false
sharing: true
footer: true

---