---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Ben Kaden"
title: "Kolumne Bibliotheksphilokartie #1: Die McLaughlin Public Library in Oshawa"
pdf: master.pdf
date: 2020-12-20
comments: false
sharing: true
footer: true

---