---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Ben Kaden"
title: "Kolumne Bibliotheksphilokartie #1: Die McLaughlin Public Library in Oshawa"
abstract: "In einer neuen Kolumne wird Ben Kaden regelmäßig eine Ansichtskarte mit Bibliotheksbezug aus seiner Sammlung kurz vorstellen."
pdf: "https://doi.org/10.18452/23478"
doi: "10.18452/23478"
date: 2020-12-20
comments: false
sharing: true
footer: true

---