---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- Michael Becht
title: "Pergament oder: Was haben Tiere jemals für uns getan?"
pdf: "master.pdf"
date: 2020-12-13
comments: false
sharing: true
footer: true

---