---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "38"
year: "2020"
contributor: 
- "Yuliya Fadeeva"
title: "Wie steht es mit Open Access in den <q>Buchfächern</q>? Erfahrungen aus dem Projekt OGeSoMo"
pdf: "https://doi.org/10.18452/23479"
doi: "10.18452/23479"
date: 2020-12-20
comments: false
sharing: true
footer: true

---